Rippling/flux-sdk

- flux_sdk/flux_core/data_models.py
- pyproject.toml
made marital status field optional in Employee model 
fix for: https://rippling.atlassian.net/browse/APPS-22645
> made marital status field optional in Employee model and fixed the typo

- .github/CODEOWNERS
- .github/workflows/lint.yml
- README.md
- flux_sdk/fertility/capabilities/report_eligibility_data/data_models.py
- flux_sdk/flex/capabilities/update_contributions/interface.py
- flux_sdk/flex/capabilities/update_enrollments/data_models.py
- flux_sdk/flex/capabilities/update_enrollments/interface.py
- flux_sdk/flux_core/data_models.py
- flux_sdk/pension/capabilities/report_payroll_contributions/data_models.py
- install_hooks.sh
- ruff.toml
- run_ruff.sh
In order to ensure that code is properly formatted, this PR adds linting with Ruff and a GitHub action to run on every commit.  Once merged, we'll add the action as a required check in order to merge PRs.
> Added linting script, run lint on PRs, and fix lint errors already in the codebase

- pyproject.toml
Bump version for fertility, for the interface change in https://github.com/Rippling/flux-sdk/pull/16
> Bump version for fertility

- flux_sdk/flex/capabilities/update_enrollments/data_models.py
- pyproject.toml
To clarify, bumping version here is for https://github.com/Rippling/flux-sdk/pull/24 , the version was not bumped in that PR
> remove internal link from comment

- flux_sdk/fertility/capabilities/report_eligibility_data/data_models.py
- flux_sdk/flux_core/data_models.py
Add new fields required for payKonnect integration
> APPS-23534 - Add new fields for payKonnect integration

- flux_sdk/flux_core/data_models.py
- flux_sdk/pension/capabilities/report_payroll_contributions/data_models.py
Added role_id in Employee class and company_id in PayrollUploadSettings.
Linked ticket: https://rippling.atlassian.net/browse/APPS-23619 
Related flux-apps PR: https://github.com/Rippling/flux-apps/pull/117
> Apps 23619: Added role_id in Employee class and company_id in PayrollUploadSettings

- flux_sdk/flex/capabilities/update_contributions/data_models.py
- flux_sdk/flex/capabilities/update_enrollments/data_models.py
- flux_sdk/flex/data_models/flex_models.py
https://rippling.atlassian.net/browse/INSURANCE-68090
> Add FSA plan type

- flux_sdk/etl/data_models/query.py
- flux_sdk/etl/data_models/tests/test_query.py
- flux_sdk/flux_core/validation.py
- pyproject.toml
https://rippling.atlassian.net/browse/APPS-23936
Currently FluxDecoder doesn't support Any field , but does support dict<str, Any>
> Update aggregate type from Any to dict<str, Any>

- flux_sdk/pension/utils/pay_konnect.py
- pyproject.toml
Division and Paygroup no longer required fields form user
> [401k] Division and Paygroup no longer required fields form user

- flux_sdk/benefits_administration/capabilities/process_employees_deductions/interface.py
- pyproject.toml
This diff releases version 0.23 in order to make the new `benefits_administration` kit available
> Release 0.23

- flux_sdk/pension/utils/pay_konnect_report_payroll_contributions.py
- pyproject.toml
https://rippling.atlassian.net/browse/BENPNP-667
- fix plan year breaking pay konnect 180
> fix plan year issue and hours_worked issues

- flux_sdk/flux_core/data_models.py
- pyproject.toml
update missing contribution types
test failures in my pr due to this: https://github.com/Rippling/rippling-main/pull/226604
> add missed contribution types

- flux_sdk/flux_core/data_models.py
- pyproject.toml
https://rippling.atlassian.net/browse/BENPNP-134, https://rippling.atlassian.net/browse/BENPNP-6
new class attributes
> update flux employee class

- flux_sdk/flex/capabilities/update_contributions/data_models.py
Jira: https://rippling.atlassian.net/browse/BENPNP-988
> add enrollment as part of contribution

- pyproject.toml
poetry update to bump flux-sdk to 0.31
> poetry update to bump flux-sdk to 0.31

- flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py
- pyproject.toml
https://rippling.atlassian.net/browse/BENEEX-1109
This adds a field to the app config which will include any fein based settings that the app has configured
> Update ben admin kit to include fein settings

- flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py
- pyproject.toml
https://rippling.atlassian.net/browse/BENPNP-1058
Add an `app_settings` field to the EE object to hold optional fields that will only be populated for certain apps
> Add app settings to ben admin kit

- flux_sdk/flex/capabilities/update_enrollments/data_models.py
- pyproject.toml
For https://rippling.atlassian.net/browse/BENFLEX-2333
Added the field `plan_year_end_date` , to accept the new field from Flex service
> Add plan year end date

- flux_sdk/flex/capabilities/update_enrollments/data_models.py
- pyproject.toml
For https://rippling.atlassian.net/browse/BENFLEX-2333
The existing fields type is wrong, should be date instead of str. Use new fields to avoid and break change
> Add new fields with correct type

- flux_sdk/time_and_attendance/capabilities/job_management/data_models.py
> [APPS-29594] add docstring for job management

- flux_sdk/time_and_attendance/capabilities/time_entry_management/data_models.py
Remove support for modified field
> remove modified query

- flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py
- pyproject.toml
JIRA: https://rippling.atlassian.net/browse/BENPNP-2026
Description: BenAdmin: SSN Field added for EmployeeHrData
> BenAdmin: SSN Field added for EmployeeHrData

- flux_sdk/time_and_attendance/capabilities/time_entry_management/data_models.py
Fix the job_attributes field naming in post_init check. Add None defaulting for optional fields.
> Fix job shift post init

- flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py
JIRA: https://rippling.atlassian.net/browse/BENPNP-2178
> Employee Hr Data data model: Rename ssn to class_code

- flux_sdk/time_and_attendance/capabilities/job_management/data_models.py
- flux_sdk/time_and_attendance/capabilities/time_entry_management/data_models.py
- flux_sdk/time_and_attendance/capabilities/time_entry_management/interface.py
- pyproject.toml
get_break_types hook and data model definitions. All details should be found in the doc string in the code; if there is anything unclear I'd like to update the doc string as well.
> get_break_types hook and data model definitions

- flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py
- flux_sdk/flux_core/data_models.py
- pyproject.toml
1. Adds Job, Department and Location Details to EmployeeHRData
> Additional Fields for Sequoia Clients. 

- flux_sdk/flux_core/data_models.py
Jira- https://rippling.atlassian.net/browse/BENPNP-2209
Added missing bulk termination in pyroll run type
> added bulk termination deduction type

- flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py
- pyproject.toml
BenAdmin report HR data capability data models : add companyEmploymentType (string label configured by company admin)
> BENPNP-3020: ben admin : add companyEmploymentType in Job model

- flux_sdk/flux_core/data_models.py
Jira- https://rippling.atlassian.net/browse/BENPNP-2790
Adding new Emergency savings account deduction type
> Added new esa deduction type

- flux_sdk/leave/capabilities/report_employees/data_models.py
- flux_sdk/leave/capabilities/report_employees/interface.py
- pyproject.toml
1. Creating a new SDK method and data models for reporting employee and beneficiary data.   
I have created the forward PRs for the app and extension code in this  [draft]PR:
https://github.com/Rippling/rippling-main/pull/298203.  Please refer to this to see how these data models will be used.     
- Version Bump to 0.51
Plan to deploy:
1. Once this lands, go to flux-apps and bump the flux-sdk version in its pyproject.toml and then run poetry.
> [LEAVE-3081] add leave flux kit 

- flux_sdk/insurance_broker/capabilities/report_employee_enrollments_to_cobra_provider/data_models.py
- pyproject.toml
https://rippling.atlassian.net/browse/BENEEX-3453
> Bump sdk version

- flux_sdk/pension/capabilities/report_payroll_contributions/data_models.py
https://rippling.atlassian.net/browse/BENPNP-1352
- Add plan comp and ytd plan comp for 401K/403B
> Add plan comp and ytd plan comp

- flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py
JIRA: https://rippling.atlassian.net/browse/BENPNP-4023
- Adds Expected Bonus to Flux Pay Model
> Adds Expected Bonus to Flux Pay Model

- flux_sdk/payroll/report_employee_ytd_data/interface.py
- pyproject.toml
(Capture the relevant artifacts in this section. Please update as "N/A" if not required)
- **JIRA:** https://rippling.atlassian.net/browse/GPDEV-36076
- **Incident Link:** N/A
- **Slack Thread:** N/A
- **Documentation/Wiki:** https://rippling.atlassian.net/wiki/spaces/ENG/pages/5025333622/Shareworks+Integration+With+Payroll
Rippling currently lacks an integration with Shareworks, Morgan Stanley’s equity compensation management platform, which is widely used by publicly traded companies in the U.S. Integrating with Shareworks is essential to support Rippling’s growth, ensure a smooth transition for customers going public, and position Rippling for its own future IPO.
**This PR addresses adding the interfaces for payroll kit related to file formatting**
- …
> GPDEV-36076 - Adding Payroll YTD Related Interfaces in Flux SDK

- flux_sdk/equity/capabilities/update_equity_grant/data_models.py
- pyproject.toml
> Add canceled quantity field to vesting event

- flux_sdk/flex/capabilities/send_cobra_enrollment_emails/interface.py
Updating SendCobraEnrollmentEmails as we need customer_settings, companyInfo while generating emails
> Update SendCobraEnrollments Interface

- flux_sdk/flex/capabilities/update_contributions/data_models.py
add employee_contribution, employer_contribution to EmployeeContribution object
> add employee_contribution, employer_contribution to EmployeeContribution object
