Rippling/flux-sdk

.github/workflows/publish.yml, DEVELOPERS.md, pyproject.toml
This PR updates the release process to be more automatic:
- each push to `main` will publish to PyPI
- the semver "major" and "minor" will come from `pyproject.toml` while the "patch" will come from `github.run_number`
=> publish new version on each push to main branch

flux_sdk/pension/capabilities/report_payroll_contributions/data_models.py, flux_sdk/pension/capabilities/report_payroll_contributions/interface.py, pyproject.toml
Also: combine the get file name hook with the format contributions hook to
avoid chatter between rippling and third party code
This name change is to better reflect the direction of information flow as we're not actually updating anything within Rippling.
=> Rename Pension kit's UpdatePayrollContributions -> ReportPayrollContributions

flux_sdk/pension/capabilities/report_payroll_contributions/data_models.py, pyproject.toml
Adding a company name field (that will use the Company name computed based on PEO, etc) to the payroll upload settings to be used in addition to the company legal name
=> APPS-22126 Transamerica PR review related changes to company name

.github/CODEOWNERS
Flux team will act as a secondary approver in addition to the apps team to ensure that contributions follow the correct conventions, naming, structure, etc.
=> Add Flux team as codeowners to the flux-sdk directory

.github/CODEOWNERS
Improper use of wildcards wasn't matching nested directories, and the flux-sdk match was overriding the global check
=> Fix codeowners syntax and cascading

flux_sdk/flux_core/data_models.py, flux_sdk/pension/utils/tests/test_ascensus/test_ascensus_180.py, flux_sdk/pension/utils/tests/test_pay_konnect/test_pay_konnect.py, pyproject.toml
- changed type of termination_date in Employee model from datetime to date
- related flux-apps PR: https://github.com/Rippling/flux-apps/pull/167
=> changed type of termination_date in Employee model from datetime to date

pyproject.toml
follow up of https://github.com/Rippling/flux-sdk/pull/70 where version bump was missed.
=> update flux-sdk version to 0.28

flux_sdk/benefits_administration/capabilities/process_employees_deductions/data_models.py, pyproject.toml
https://rippling.atlassian.net/browse/BENPNP-1129
This diff adds support in the ben admin kit data model for imputed income to be handled apart from EE and company contributions
=> Add imputed income to ben admin kit data models

flux_sdk/flux_core/data_models.py, pyproject.toml
https://rippling.atlassian.net/browse/BENPNP-1359
This diff adds the `phone_number_v2` field to `Employee` to support an object representation of international phone numbers. This mirrors the HRIS support here https://github.com/Rippling/rippling-main/blob/master/app/hub/models/phone_number.py#L12
=> Add phone_number_v2

flux_sdk/time_and_attendance/capabilities/job_management/data_models.py, flux_sdk/time_and_attendance/capabilities/job_management/interface.py
Here we add a new kit called `time_and_attendance`.
For the `job_management` capability, we define a hook called `get_job_attributes`
This is what third party developers will use to call their APIs and return their 3P job attributes, along with rippling mapping.
Example response:
```
attributes = [
Attribute(
id="job_title",
name="Job title",
description="Qubeyond job title attribute",
matching_rippling_attribute=[RipplingAttribute.PAY_RATE]
),
Attribute(
id="location",
name="Location",
description="Qubeyond location attribute",
matching_rippling_attribute=[RipplingAttribute.WORK_LOCATION, 
RipplingAttribute.JOB_SITE_LOCATION]
),
]
```
We enforce that `id` and `name` cannot repeat.
=> [APPS-29594] add job management sdk for t&a kit

flux_sdk/time_and_attendance/capabilities/job_management/data_models.py
Add the id field to the AttributeValue class so that we can have a more unique identifier for each attribute value from the third party.
=> Add the id field to the AttributeValue class

flux_sdk/pension/capabilities/report_payroll_contributions/data_models.py, pyproject.toml
https://rippling.atlassian.net/browse/BENPNP-2343
I am adding id field in PayrollRunContribution as a part of above ticket. Since we need to support multi loans hence need to add id to distinguish diff loans.
=> Adding id to support multi loan 401k

flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py, pyproject.toml
Fix typo in company_employment_type attribute of JobDetail model
PR with typo : https://github.com/Rippling/flux-sdk/pull/105
=> BENPNP-3020: fix: typo in JobDetail attribute company_employment_type

flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py
Problem Statement: 
We have some user defined custom fields defined for companies in the CustomFieldsV2  Model, some vendors (namely Plansource) desire the values of these field for each role, and this needs to be passed to flux-apps, so as to include them in the Census File. 
The Changes allow us to pass the Custom Field Names and their values to flux-apps.
=> Adds dynamic fields for specific vendors

flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py, flux_sdk/flux_core/data_models.py, pyproject.toml
JIRA: https://rippling.atlassian.net/browse/BENPNP-3420
Description:
Added 2 fields:
- permanent_profile_number - corresponds to unique id for a person across multiple roles in the same company
- work_location.nickname - manually provided nickname for a work location
=> BENPNP-3420: add work location nickname and perm profile

flux_sdk/benefits_administration/capabilities/report_employees_hr_data/data_models.py, pyproject.toml
JIRA: https://rippling.atlassian.net/browse/BENPNP-3371
We are migrating 3p BenAdmin apps to support decimal point in weekly hours. 
I have introduced a new field and marked the old one as deprecated. 
We will move our apps to use the new field one by one.
=> BENPNP-3371: support for decimal precision in weeklyHours

flux_sdk/flux_core/data_models.py, pyproject.toml
This is a breaking change. but since none of the apps in production using it. It is safe to change now.
=> Add support for report field names in Report data

flux_sdk/payroll/report_employee_ytd_data/interface.py, pyproject.toml
(Capture the relevant artifacts in this section. Please update as "N/A" if not required)
- **JIRA:** 
- **Incident Link:** 
- **Slack Thread:** 
- **Documentation/Wiki:** N/A
While developing the payroll kit, I discovered that interface names are automatically converted to snake_case. As a result, ReportEmployeeYTDData was incorrectly transformed into report_employee_y_t_d, causing module resolution to fail.
✅ This PR resolves the issue by updating the class name to ReportEmployeeYtdData, ensuring consistent and correct formatting.
- `flux_sdk/payroll/report_employee_ytd_data/interface.py` - Renaming the ReportEmployeeYTDData interface to ReportEmployeeYtdData
- `pyproject.toml` - Bumping the version of flux-sdk
- I've tested it locally and it works as expected. 
- NA
- NA
=> Fix incorrect snake_case conversion for YTD in interface name

flux_sdk/insurance_broker/capabilities/report_employee_enrollments_to_cobra_provider/data_models.py, pyproject.toml
This diff adds a new enum value to the Benefits `EnrollmentEventReason` to cover any case where the reason is indeterminable.
=> Add enum type for benefits

flux_sdk/insurance_broker/capabilities/upload_census_data/data_models.py
This pull request updates the `MemberData` class in the `flux_sdk/insurance_broker/capabilities/upload_census_data/data_models.py` file by adding new attributes related to plan details.
* Added `role_status` to represent the member's role status.
* Added `plan_effective_date` to capture the effective date of the plan.
* Added `plan_deduction_frequency` to specify the frequency of plan deductions.
=> add field to MemberData
